const nationality = {
  Afghan: "AF",
  Albanian: "AL",
  Algerian: "DZ",
  American: "US",
  Andorran: "AD",
  Angolan: "AO",
  Anguillan: "AI",
  Argentine: "AR",
  Armenian: "AM",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bahamian: "BS",
  Bahraini: "BH",
  Bangladeshi: "BD",
  Barbadian: "BB",
  Belarusian: "BY",
  Belgian: "BE",
  Belizean: "BZ",
  Beninese: "BJ",
  Bermudian: "BM",
  Bhutanese: "BT",
  Bolivian: "BO",
  Botswanan: "BW",
  Brazilian: "BR",
  British: "GB",
  "British Virgin Islander": "VG",
  Bruneian: "BN",
  Bulgarian: "BG",
  Burkinan: "BF",
  Burmese: "MM",
  Burundian: "BI",
  Cambodian: "KH",
  Cameroonian: "CM",
  Canadian: "CA",
  "Cape Verdean": "CV",
  "Cayman Islander": "KY",
  "Central African": "CF",
  Chadian: "TD",
  Chilean: "CL",
  Chinese: "CN",
  "Citizen of Antigua and Barbuda": "AG",
  "Citizen of Bosnia and Herzegovina": "BA",
  "Citizen of Guinea-Bissau": "GW",
  "Citizen of Kiribati": "KI",
  "Citizen of Seychelles": "SC",
  "Citizen of the Dominican Republic": "DO",
  "Citizen of Vanuatu ": "VU",
  Colombian: "CO",
  Comoran: "KM",
  "Congolese (Congo)": "CG",
  "Congolese (DRC)": "CD",
  "Cook Islander": "CK",
  "Costa Rican": "CR",
  Croatian: "HR",
  Cuban: "CU",
  Cymraes: "GB",
  Cymro: "GB",
  Cypriot: "CY",
  Czech: "CZ",
  Danish: "DK",
  Djiboutian: "DJ",
  Dominican: "DM",
  Dutch: "NL",
  "East Timorese": "TL",
  Ecuadorean: "EC",
  Egyptian: "EG",
  Emirati: "AE",
  English: "GB",
  "Equatorial Guinean": "GQ",
  Eritrean: "ER",
  Estonian: "EE",
  Ethiopian: "ET",
  Faroese: "FO",
  Fijian: "FJ",
  Filipino: "PH",
  Finnish: "FI",
  French: "FR",
  Gabonese: "GA",
  Gambian: "GM",
  Georgian: "GE",
  German: "DE",
  Ghanaian: "GH",
  Gibraltarian: "GI",
  Greek: "GR",
  Greenlandic: "GL",
  Grenadian: "GD",
  Guamanian: "GU",
  Guatemalan: "GT",
  Guinean: "GN",
  Guyanese: "GY",
  Haitian: "HT",
  Honduran: "HN",
  "Hong Konger": "HK",
  Hungarian: "HU",
  Icelandic: "IS",
  Indian: "IN",
  Indonesian: "ID",
  Iranian: "IR",
  Iraqi: "IQ",
  Irish: "IE",
  Israeli: "IL",
  Italian: "IT",
  Ivorian: "CI",
  Jamaican: "JM",
  Japanese: "JP",
  Jordanian: "JO",
  Kazakh: "KZ",
  Kenyan: "KE",
  Kittitian: "KN",
  Kosovan: "",
  Kuwaiti: "KW",
  Kyrgyz: "KG",
  Lao: "",
  Latvian: "LV",
  Lebanese: "LB",
  Liberian: "LR",
  Libyan: "LY",
  "Liechtenstein citizen": "LI",
  Lithuanian: "LT",
  Luxembourger: "LU",
  Macanese: "MO",
  Macedonian: "MK",
  Malagasy: "MG",
  Malawian: "MW",
  Malaysian: "MY",
  Maldivian: "MV",
  Malian: "ML",
  Maltese: "MT",
  Marshallese: "MH",
  Martiniquais: "MQ",
  Mauritanian: "MR",
  Mauritian: "MU",
  Mexican: "MX",
  Micronesian: "FM",
  Moldovan: "MD",
  Monegasque: "MC",
  Mongolian: "MN",
  Montenegrin: "ME",
  Montserratian: "MS",
  Moroccan: "MA",
  Mosotho: "LS",
  Mozambican: "MZ",
  Namibian: "NA",
  Nauruan: "NR",
  Nepalese: "NP",
  "New Zealander": "NZ",
  Nicaraguan: "NI",
  Nigerian: "NG",
  Nigerien: "NE",
  Niuean: "NU",
  "North Korean": "KP",
  "Northern Irish": "GB",
  Norwegian: "NO",
  Omani: "OM",
  Pakistani: "PK",
  Palauan: "PW",
  Palestinian: "PS",
  Panamanian: "PA",
  "Papua New Guinean": "PG",
  Paraguayan: "PY",
  Peruvian: "PE",
  "Pitcairn Islander": "PN",
  Polish: "PL",
  Portuguese: "PT",
  Prydeinig: "GB",
  "Puerto Rican": "PR",
  Qatari: "QA",
  Romanian: "RO",
  Russian: "RU",
  Rwandan: "RW",
  Salvadorean: "SV",
  Sammarinese: "SM",
  Samoan: "WS",
  "Sao Tomean": "ST",
  "Saudi Arabian": "SA",
  Scottish: "GB",
  Senegalese: "SN",
  Serbian: "RS",
  "Sierra Leonean": "SL",
  Singaporean: "SG",
  Slovak: "SK",
  Slovenian: "ST",
  "Solomon Islander": "SB",
  Somali: "SO",
  "South African": "ZA",
  "South Korean": "KR",
  "South Sudanese": "SS",
  Spanish: "ES",
  "Sri Lankan": "LK",
  "St Helenian": "SH",
  "St Lucian": "LC",
  Stateless: null,
  Sudanese: "SD",
  Surinamese: "SR",
  Swazi: "SZ",
  Swedish: "SE",
  Swiss: "CH",
  Syrian: "SY",
  Taiwanese: "TW",
  Tajik: "TJ",
  Tanzanian: "TZ",
  Thai: "TH",
  Togolese: "TG",
  Tongan: "TO",
  Trinidadian: "TT",
  Tristanian: "SH",
  Tunisian: "TN",
  Turkish: "TR",
  Turkmen: "TM",
  "Turks and Caicos Islander": "TC",
  Tuvaluan: "TV",
  Ugandan: "UG",
  Ukrainian: "UA",
  Uruguayan: "UY",
  Uzbek: "UZ",
  "Vatican citizen": "VA",
  Venezuelan: "VE",
  Vietnamese: "VN",
  Vincentian: "VC",
  Wallisian: "WF",
  Welsh: "GB",
  Yemeni: "YE",
  Zambian: "ZM",
  Zimbabwean: "ZW",
}

export default value => nationality[value]
